/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    BadgeItem: typeof import('./src/components/badges/BadgeItem.vue')['default']
    BadgesTable: typeof import('./src/components/admin/BadgesTable.vue')['default']
    ChangePasswordModal: typeof import('./src/components/ChangePasswordModal.vue')['default']
    CreateCanvas: typeof import('./src/components/create/CreateCanvas.vue')['default']
    CreateMenu: typeof import('./src/components/create/CreateMenu.vue')['default']
    CreateMenuBorder: typeof import('./src/components/create/partials/CreateMenuBorder.vue')['default']
    CreateMenuCanvas: typeof import('./src/components/create/partials/CreateMenuCanvas.vue')['default']
    CreateMenuDrafts: typeof import('./src/components/create/partials/CreateMenuDrafts.vue')['default']
    CreateMenuImport: typeof import('./src/components/create/partials/CreateMenuImport.vue')['default']
    CreateMenuInsert: typeof import('./src/components/create/partials/CreateMenuInsert.vue')['default']
    CreateMenuShapes: typeof import('./src/components/create/partials/CreateMenuShapes.vue')['default']
    CreateMenuText: typeof import('./src/components/create/partials/CreateMenuText.vue')['default']
    CreateSave: typeof import('./src/components/create/CreateSave.vue')['default']
    CreateUndo: typeof import('./src/components/create/CreateUndo.vue')['default']
    Cta: typeof import('./src/components/home/Cta.vue')['default']
    DashOptions: typeof import('./src/components/DashOptions.vue')['default']
    Features: typeof import('./src/components/home/Features.vue')['default']
    FeaturesItem: typeof import('./src/components/home/FeaturesItem.vue')['default']
    FeaturesSection: typeof import('./src/components/home/FeaturesSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    LoginFormMobile: typeof import('./src/components/login/LoginFormMobile.vue')['default']
    ManageBadgeItem: typeof import('./src/components/badges/ManageBadgeItem.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavbarLinks: typeof import('./src/components/NavbarLinks.vue')['default']
    NavbarLinksMobile: typeof import('./src/components/NavbarLinksMobile.vue')['default']
    PendingBadgesTable: typeof import('./src/components/admin/PendingBadgesTable.vue')['default']
    RegisterForm: typeof import('./src/components/login/RegisterForm.vue')['default']
    RegisterFormMobile: typeof import('./src/components/login/RegisterFormMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextSection: typeof import('./src/components/TextSection.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorPicker: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue')['default']
    UFieldGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
    UListbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Listbox.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPageCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    URadioGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UsersTable: typeof import('./src/components/admin/UsersTable.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTimeline: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
